[target.'cfg(target_family = "windows")']
rustflags = ["-Ctarget-feature=+crt-static"]

[target.aarch64-linux-android]
ar = '../../Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar'
linker = '../../Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang'

[target.armv7-linux-androideabi]
ar = '../../Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar'
linker = '../../Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi34-clang'

[target.i686-linux-android]
ar = '../../Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-ar'
linker = '../../Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android34-clang'

[target.x86_64-linux-android]
ar = '../../Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-ar'
linker = '../../Android/Sdk/ndk/26.0.10404224/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android34-clang'
