[package]
name = "demo"
version = "0.1.0"
authors = ["xthexder", "nauscar"]
edition = "2021"
license-file = "../../LICENSE-MPL-2.0"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[[bin]]
name = "demo-desktop"
path = "gen/bin/desktop.rs"

[dependencies]
strayphotons = { version = "*", path = "../../strayphotons" }

[package.metadata.android.sdk]
min_sdk_version = 29
target_sdk_version = 34
