[package]
name = "demo"
version = "0.1.0"
authors = ["xthexder", "nauscar"]
edition = "2021"
license-file = "../../LICENSE-MPL-2.0"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[[bin]]
path = "src/desktop.rs"
name = "demo-desktop"

[dependencies]
strayphotons = { version = "*", path = "../../strayphotons" }

[package.metadata.android]
pagkage = "net.strayphotons.demo"
build_targets = ["aarch64-linux-android"]
assets = "assets"
apk_name = "Demo"
runtime_libs = "app/src/main/jniLibs"

[package.metadata.android.sdk]
min_sdk_version = 29
target_sdk_version = 34

[[package.metadata.android.uses_feature]]
name = "android.hardware.vulkan.level"
required = true
version = 1
