[package]
name = "demo"
version = "0.1.0"
authors = ["xthexder", "nauscar"]
edition = "2021"
license-file = "../../LICENSE-MPL-2.0"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[[bin]]
name = "demo-desktop"
path = "gen/bin/desktop.rs"

[dependencies]
sp-sys = { version = "*", path = "../../sp-sys" }
log = "0.4"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13"
android-activity = { version = "0.5.0-beta.1", features = ["native-activity"] }

[target.'cfg(not(target_os = "android"))'.dependencies]
simple_logger = "4.2"

[package.metadata.android.sdk]
min_sdk_version = 24
target_sdk_version = 34
